---
- name: Setup RaspberryPies basics
  hosts: masters
  remote_user: ubuntu

  roles:
    - common/update
    - common/hostname

    - role: common/sudoers
      vars:
        - security_sudoers_passwordless: [ubuntu]
