---
name: Linting
on:
  workflow_call:
jobs:
  pre-commit-ci:
    name: Pre-Commit
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: "3.10"

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip' # caching pip dependencies

      - name: Cache pip
        uses: actions/cache@v3.3.1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('./requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache Ansible
        uses: actions/cache@v3.3.1
        with:
          path: ~/.ansible/collections
          key: ${{ runner.os }}-ansible-${{ hashFiles('collections/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-ansible-

      - name: Install dependencies
        run: |
          echo "::group::Upgrade pip"
          python3 -m pip install --upgrade pip
          echo "::endgroup::"

          echo "::group::Install Python requirements from ansible/requirements.txt"
          python3 -m pip install -r ansible/requirements.txt
          echo "::endgroup::"

          echo "::group::Install Ansible role requirements from ansible/collections/requirements.yml"
          ansible-galaxy install -r ansible/collections/requirements.yml
          echo "::endgroup::"

      - name: Run pre-commit
        uses: pre-commit/action@646c83fcd040023954eafda54b4db0192ce70507 # 3.0.0
